include: package:flutter_lints/flutter.yaml

name: your_project_name
description: A new Flutter project

# The version of the project
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # Add any other dependencies you need
  carousel_slider: ^4.0.0  # For the onboarding carousel

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # The assets to include in the project (your images)
  assets:
    - assets/logo.png
    - assets/onboarding_image.png
    - assets/geoat_earth.png
    - assets/Splash.png
    - assets/Splash2.png
    - assets/Splash3.png
    - assets/Splash3.jpg
    - assets/profile.jpeg

  uses-material-design: true


   # Path to your icon file

