include: package:flutter_lints/flutter.yaml

name: your_project_name
description: A new Flutter project

# The version of the project
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.50.6  
  timeline_tile: 2.0.0


  # Add any other dependencies you need

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Recommended lints package for Flutter projects
  # Add any other dev dependencies

flutter:

  # The assets to include in the project (images, icons, etc.)
  assets:
    - assets/logo.png
    - assets/onboarding_image.png
    - assets/geoat_earth.png
    - assets/Splash.png
    - assets/Splash2.png
    - assets/Splash3.png
    - assets/Splash3.jpg
    - assets/profile.jpeg

  uses-material-design: true  # Enables Material Design in the app

# If you are configuring app icons with `flutter_launcher_icons`, do it here:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Splash3.png"

